// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdNflBY4N8yKtNWKMN7DtQ-604ScITyTw',
    appId: '1:525559107604:web:32cd2e1772bd259af09701',
    messagingSenderId: '525559107604',
    projectId: 'aqshal-sehatinaja',
    authDomain: 'aqshal-sehatinaja.firebaseapp.com',
    storageBucket: 'aqshal-sehatinaja.firebasestorage.app',
    measurementId: 'G-RGGGT9FBZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfWyecFcEjU9099SjXeqfysAwTt5iM2I',
    appId: '1:525559107604:android:ca5c17a56150c6c1f09701',
    messagingSenderId: '525559107604',
    projectId: 'aqshal-sehatinaja',
    storageBucket: 'aqshal-sehatinaja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSDmLE_KGa0ln90MXXWRJEVicogr1Nnw',
    appId: '1:525559107604:ios:6710673bbe776b08f09701',
    messagingSenderId: '525559107604',
    projectId: 'aqshal-sehatinaja',
    storageBucket: 'aqshal-sehatinaja.firebasestorage.app',
    iosBundleId: 'com.example.projectPpkd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdNflBY4N8yKtNWKMN7DtQ-604ScITyTw',
    appId: '1:525559107604:web:590b3ee6751ddb4df09701',
    messagingSenderId: '525559107604',
    projectId: 'aqshal-sehatinaja',
    authDomain: 'aqshal-sehatinaja.firebaseapp.com',
    storageBucket: 'aqshal-sehatinaja.firebasestorage.app',
    measurementId: 'G-Y1385LST2R',
  );
}
